/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectosRoute,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProyectosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/stack': typeof StackRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sobre-mi': typeof SobreMiRoute
  '/stack': typeof StackRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos': typeof ProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/stack': typeof StackRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/proyectos'
    | '/sobre-mi'
    | '/stack'
    | '/proyectos/$slug'
    | '/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/sobre-mi'
    | '/stack'
    | '/proyectos/$slug'
    | '/proyectos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/proyectos'
    | '/sobre-mi'
    | '/stack'
    | '/proyectos/$slug'
    | '/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ProyectosRoute: typeof ProyectosRouteWithChildren
  SobreMiRoute: typeof SobreMiRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof ProyectosRoute
    }
  }
}

interface ProyectosRouteChildren {
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosSlugRoute: ProyectosSlugRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ProyectosRoute: ProyectosRouteWithChildren,
  SobreMiRoute: SobreMiRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
